copy (pasdev16)QSUBST.TYP     , same
copy (pasdev16)QSUBST.PAS     , same
copy (pasdev16)QEDOVL.COM     , same
copy (pasdev16)QEDDEL.COM      , same
copy (pasdev16)QEDVAX.COM      , same
copy (pasdev16)QNCOVL.COM     , same
copy (pasdev16)QREAD.PAS     , same
copy (pasdev16)QEDLN.PAS    , same
copy (pasdev16)QED.INC     , same
copy (pasdev16)QLINE.TYP      , same
copy (pasdev16)QLD.PAS      , same
copy (pasdev16)QJOIN.PAS      , same
