$header dcext.hdr

$INCLUDE DTIME.TYP

TYPE
   INT = MININT..MAXINT;
   STR2 = STRING[2];
   STR3 = STRING[3];
   STR11 = STRING[11];

EXTERNAL FUNCTION DC_DTIME(DTIME: DTIME_INT): DTIMEREC;
EXTERNAL FUNCTION CHARS2(INT_VAL: INT): STR2;
EXTERNAL FUNCTION DC_MONTH(INT):STR3;
EXTERNAL FUNCTION CV_BIN_STR(INT):STR11;


PUBLIC FUNCTION DC_EXT(DTIME: DTIME_INT): DTIME_EXT;

VAR
   DTIME_BIN: DTIMEREC;


BEGIN
   DTIME_BIN := DC_DTIME(DTIME); (* FIRST CONVERT TO BINARY *)

   WITH DTIME_BIN DO

   BEGIN
      DC_EXT := CHARS2(DAY) || '-';
      DC_EXT[4:4] := DC_MONTH(MONTH) || '-';
      DC_EXT[8:2] := SUBSTR(CV_BIN_STR(YEAR),3,2);
      DC_EXT[10:4] := ' ' || CHARS2(HOURS) || ':';
      DC_EXT[14:3] := CHARS2(MINS) || ':' ;
      DC_EXT[17:2] := CHARS2(SECS)
   END

END.
