C-      FORTRAN EXTENDED PRECISION ROUTINES
C-  
C-  These routines are used by genlib to do basic arithmetic in
C-  extended precision format.  The pascal cannot compute values
C-  as precisely as the high precision library, so the 
C-  math test library is generated by using the high precision
C-  library through fortran.
C-
C-  The below procedures are self-explanatory.
C-
       SUBROUTINE MTH_HADD(HRSLT,HARG1,HARG2)
       REAL*16 HRSLT,HARG1,HARG2
C-
       HRSLT = HARG1 + HARG2
C-
       RETURN
       END
C-
C-
       SUBROUTINE MTH_HSUB(HRSLT,HARG1,HARG2)
       REAL*16 HRSLT,HARG1,HARG2
C-
       HRSLT = HARG1 - HARG2
C-
       RETURN
       END
C-
C-
       SUBROUTINE MTH_HMULT(HRSLT,HARG1,HARG2)
       REAL*16 HRSLT,HARG1,HARG2
C-
       HRSLT = HARG1 * HARG2
C-
       RETURN
       END
C-
C-
       SUBROUTINE MTH_HDIV(HRSLT,HARG1,HARG2)
       REAL*16 HRSLT,HARG1,HARG2
C-
       HRSLT = HARG1 / HARG2
C-
       RETURN
       END
C-
C-
       SUBROUTINE MTH_HPWR(HRSLT,HARG1,HARG2)
       REAL*16 HRSLT,HARG1,HARG2
C-
       HRSLT = HARG1 ** HARG2
C-
       RETURN
       END
C-
C-
       SUBROUTINE MTH_HIPWR(IRSLT,HARG1,HARG2)
       INTEGER IRSLT
       REAL*16 HARG1,HARG2
C-
       IRSLT = HARG1 ** HARG2
C-
       RETURN
       END
C-
C-
       SUBROUTINE MTH_HPWRI(HRSLT,HARG1,IARG2)
       REAL*16 HRSLT,HARG1
       INTEGER IARG2
C-
       HRSLT = HARG1 ** IARG2
C-
       RETURN
       END
C-
C- 
       SUBROUTINE MTH_HSIGN(ISIGN,HREAL)
       INTEGER ISIGN
       REAL*16 HREAL
C-
       ISIGN = 1
       IF (HREAL.LT.0) ISIGN = -1
C-
       RETURN
       END
