copy (pasdev10)M68OPT.PAS+M68SET.PAS+P10CG.TYP+P10CGU.INC+P10CGU.PAS+P10REL.PAS+PASBOD.PAS+PASEMU.INC+PASEMU.PAS+PASESM.PAS,same
copy (pasdev10)PASOPT.PAS+PASREF.PAS+PASSFC.PAS+Q10GEN.INC+Q10GEN.PAS+VAXCG.TYP+VAXCGU.INC+VAXCGU.PAS+VAXGEN.INC+VAXGEN.PAS,same
