DO QED
L PASERR.TYP
1,3 D
W PASERR.LST
Y
Q
DO TRNSLT
PASERR.LST=PASERR.LST/A-Z=#A-#Z
PASERR.LST=PASERR.LST/%#A-#Z_=@N

PDP
R TECO
ERPASERR.LSTEWPASERR.LSTYL.-2"E-K'J-1U1<<%1\I .U20L4-Q2+.<I >L.-Z;>P.-Z;>EX
XEX
R SORT
PASERR.LST=PASERR.LST/K5.10/R40
/EXIT
DO RUNCOP
RNF
PASERR.LST/AUTOFF

