RENAME *.LST AS *.LPT
FILES PRINT.TMP=*.LPT/STORAGE/REVERSE/SIZE
DO QED
L PRINT.TMP
1,5D
P
2,$D
F::SPL" "D;.D;.COP I.;S::PRINT CDC%=:;S"%":";S@@.LPT/FULLCH/SIZE 105$MDSI@;.+1S::DELETE :;S@@.LPT$R(UPL)COM;PRINT$@;.-1,.SPL"$"A,D
N
$A
&&WAIT&&
.
1F/&&WAIT&&/.I PRWAIT.COM
N
$D
W

Q
R(UPL)COM;PRINT.TMP

