PROGRAM UNIQUE;

CONST STR_SIZE = 256;
      END_FILE = CHR(28);

TYPE STR_PARM = STRING [STR_SIZE];

VAR S1, S2: STR_PARM;

PROCEDURE READ_STRING ( VAR S: STR_PARM );
VAR BUF: PACKED ARRAY [1..STR_SIZE] OF CHAR;
    IND: 0 .. STR_SIZE;
BEGIN
  IF EOF(INPUT) THEN
    S := END_FILE
  ELSE BEGIN
    IND := 0;
    WHILE NOT EOLN(INPUT) DO BEGIN
      IF IND <> STR_SIZE THEN BEGIN
	IND := IND + 1;
	BUF [IND] := INPUT^;
      END;
      GET (INPUT);
    END;
    READLN (INPUT);
    S := SUBSTR(BUF,1,IND);
  END;
END (* READ_STRING *);

EXTERNAL PROCEDURE GETIOFILES;

BEGIN
  LOOP
    OPEN (TTY);
    REWRITE (TTY);
    GETIOFILES;
    READ_STRING (S1);
    REPEAT
      WRITELN (OUTPUT,S1);
      REPEAT
	READ_STRING (S2);
      UNTIL S2 <> S1;
      S1 := S2;
    UNTIL S1 = END_FILE;
    CLOSE (OUTPUT);
  END;
END (* UNIQUE *).
