PROGRAM ASMD_TEST;

VAR ARG1, ARG2: MINIMUM(REAL)..MAXIMUM(REAL) PREC 16;
    CORD: INTEGER;
    OPERATION: CHAR;

BEGIN
OPEN(TTY);
REWRITE(TTY);
WRITELN(TTY,'ASMD TEST');

REPEAT
   WRITE(TTY,'}');
   BREAK(TTY);
   READLN(TTY);
   READ(TTY,ARG1,OPERATION,ARG2);
   writeln(tty,arg1,operation,arg2,' =');
   WRITELN(TTY,ARG1:20,OPERATION,ARG2:20,' =');
   WRITELN(TTY,ARG1:20:10,OPERATION,ARG2:20:10,' =');
   writeln(tty,arg1:99:1,operation,arg2:20:2,' =');
   WRITELN(TTY,ARG1:20:10:E,OPERATION,ARG2:20:10:E,' =');
   CORD := ORD(OPERATION);
   CASE CORD OF
     43: WRITELN(TTY,ARG1+ARG2);
     45: WRITELN(TTY,ARG1-ARG2);
     42: WRITELN(TTY,ARG1*ARG2);
     47: WRITELN(TTY,ARG1/ARG2);
     OTHERS: ;
   END;
UNTIL FALSE;
END.
